### PR TITLE
Dandi2k8's Contribution: Part 1

### PR DESCRIPTION
**Pull request by DRD2k8**
My first part of the continuation.

### CODE REVIEW

**Comment by itsmeteddyhere** [comment]
Cool that someone wants to continue this. You should probably make your own repo and mod pages for this, since I don't want to take credit for your work. If you want, I can link to your continuation on my curseforge and modrinth pages. Probably will not be merging it, like I said make your own repo, I don't want to manage this mod anymore.

**Comment by DRD2k8** [comment]
In the future, I plan to add the missing wood pieces to the Glacian, Aeronos, and Strophar trees & mushrooms. And I also will make those trees & mushrooms generatable. Anyway, I'll continue working on my fork.

**Comment by itsmeteddyhere** [comment]
this is so cool, you should probably change the project structure to net.dandi2k8.ad_extendra. Do you have a curseforge page for it or something

**Comment by itsmeteddyhere** [comment]
I'm not merging this, it's your project now and it should get treated like it is. Good luck with it!

**Comment by itsmeteddyhere** [comment]
I hope I didn't just delete your fork by closing this

**Pull request closed without merging**
